apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  labels:
    app: emby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      initContainers:
      - name: change-priveleges
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "chown -R 2580:2580 /programdata"]
        volumeMounts:
        - name: programdata
          mountPath: /programdata
      containers:
      - name: emby
        image: emby/embyserver
        imagePullPolicy: Always
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: programdata
          mountPath: /programdata
        - name: tv
          mountPath: /tv
        - name: movies
          mountPath: /movies
      volumes:
      - name: programdata
        emptyDir: {}
      - name: tv
        emptyDir: {}
      - name: movies
        emptyDir: {}